### ISSUE TITLE
Attached RTF causes parser to segfault

### ISSUE THREAD

**Issue by gcasa** [gnustep/libs-gui#107]
The attached RTF file causes the RTF parser to segfault when trying to load with Ink.
[sample.rtf.gz](https://github.com/gnustep/libs-gui/files/6719652/sample.rtf.gz)

**Comment by gcasa** [comment]
I have added a quick fix to master to prevent a crash when this happens.  I suspect it is due to the presence of a table in the RTF being parsed.   This, however, should still be fixed.

**Comment by fredkiefer** [comment]
Hi Greg,

your fix is not just a work around, it is a good fix that should stay in place. I inspected this issue last night and came up with something similar. What happens here is that some sort of field gets used in the RTF and this uses a variant of field parameters that is not supported by our RTF grammar.  That way the code ends up in an error state and for this case NULL is returned as the value of this statement. Your fix prevents that values from getting used in later code.
A better fix would require to understand what additional case for the field values is missing here and how to handle these. But even then preventing a still possible NULL value from getting used is the right thing to do. What could be improved is the error message you are printing out. In a few days from now even you won't remember what that means.

**Comment by gcasa** [comment]
> Hi Greg,
> 
> your fix is not just a work around, it is a good fix that should stay in place. I inspected this issue last night and came up with something similar. What happens here is that some sort of field gets used in the RTF and this uses a variant of field parameters that is not supported by our RTF grammar. That way the code ends up in an error state and for this case NULL is returned as the value of this statement. Your fix prevents that values from getting used in later code.
> A better fix would require to understand what additional case for the field values is missing here and how to handle these. But even then preventing a still possible NULL value from getting used is the right thing to do. What could be improved is the error message you are printing out. In a few days from now even you won't remember what that means.

I've been pretty busy with $dayjob stuff, so I just saw this.  I will review and update the error message.   BTW, I have been thinking for some time about adding more parsers, so that GS can read other formats (DOC or DOCX for instance) but that is low priority at the moment.

**Comment by gcasa** [comment]
I've improved the error message.
