### ISSUE TITLE
ISO 630 and 693-2 .lproj directories in bundle (en, fr, ...)

### ISSUE THREAD

**Issue by gcasa** [gnustep/libs-gui#135]
Currently GNUstep uses the full name of the language for the .lproj directory.   In addition to this we should also support the 2 or 3 letter language codes described in ISO 630 and ISO 639-2.     This is the same thing Apple now uses.  I am saying we should support both. :)

**Comment by gcasa** [comment]
To clarify, this issue is about using two character language codes, as well as the full names we currently have for languages.

**Comment by fredkiefer** [comment]
Is this still up to date? I just checked the NSBundle code in base and this looks like it is capable of loading resources with different forms of language names. Do you have code to test this behaviour? And why did you report it as a gui issue in the first place? Is there a layer on top where gui fails to provide the behaviour offered by base?

**Comment by gcasa** [comment]
I haven't tested this as of late.  I am not sure if it's still relevant.  If someone did implement this, then they didn't update this issue. :)

**Comment by fredkiefer** [comment]
The code in NSBundle to support different names for languages has been there for eleven years. Could you please write a test what is still missing and clarify in this bug report?

**Comment by gcasa** [comment]
I have tested this.  It appears to be supported now.  Thanks.  GC
