### ISSUE TITLE
horizontal window resizing broken with GS handles window decoration

### ISSUE THREAD

**Issue by rmottola** [gnustep/libs-gui#136]
Resizing windows horizontally with GS handles window decorations does not work anymore.

A rough bisection of gui and back, shows that GUI

commit 77202f52e1963bdfebc2547b66b8803cc3a6aa03 (HEAD)
Author: Gregory John Casamento <greg.casamento@gmail.com>
Date:   Wed Dec 1 19:44:43 2021 -0500

    Update ChangeLog for NSSplitView change

**Comment by gcasa** [comment]
> Resizing windows horizontally with GS handles window decorations does not work anymore.
> 
> A rough bisection of gui and back, shows that GUI
> 
> commit [77202f5](https://github.com/gnustep/libs-gui/commit/77202f52e1963bdfebc2547b66b8803cc3a6aa03) (HEAD) Author: Gregory John Casamento [greg.casamento@gmail.com](mailto:greg.casamento@gmail.com) Date: Wed Dec 1 19:44:43 2021 -0500
> 
> ```
> Update ChangeLog for NSSplitView change
> ```

I believe you mean that this is the commit at which it works, and not the one at which it was broken. :)   Just saying. :D

**Comment by rmottola** [comment]
Yes, at that commit it still worked.

**Comment by rmottola** [comment]
There was a lot of breakage in GUI that makes compilation fail, so true bisecting is hard.

Was already broken:
`commit b84d8cc3fd4eb198b2021ebed2b03fd942802620 (HEAD)
Author: Fred Kiefer <fredkiefer@gmx.de>
Date:   Tue Dec 28 17:23:48 2021 +0100

    * Headers/Additions/GNUstepGUI/GSWindowDecorationView.h:
    Move new addon methods for Wayland to correct class
    GSStandardWindowDecorationView.
    * Source/GSWindowDecorationView.m: Keep variables declarations together.
`

Before that I get compilation errors until I go back to 1st of December.... it should help frame in things to these DecorationView changes.

**Comment by rmottola** [comment]
Fixed with https://github.com/gnustep/libs-gui/commit/96db5bf89cdc913555d3a0b21edca09108d0fb36
