### ISSUE TITLE
GUI Documentation is BROKEN....

### ISSUE THREAD

**Issue by gcasa** [gnustep/libs-gui#198]
Steps to reproduce...

1. make sure you have the requisites for autogsdoc installed
2. go into libs-gui
3. cd Documentation
4. make
5. open index.html with your preferred browser...

Result...  (see attached) 
![GUI_Documentation_Broken](https://github.com/gnustep/libs-gui/assets/27943/342f1439-7798-4193-bf79-5b9117f96b04)

Expected... you should get a complete list of classes and protocols in GUI/AppKit

**Comment by rfm** [comment]
A new preprocessor value was added to the headers without telling the document generation how to handle it.
I mapped it to an empty string.

**Comment by gcasa** [comment]
Sweet!!   Thank you
