### ISSUE TITLE
GSTheme should have more hooks in NSView subclasses

### ISSUE THREAD

**Issue by KyleCardoza** [gnustep/libs-gui#200]
Title says it all, really - I think that GSTheme's infrastructure should have methods for modifying more aspects of the visual presentation of NSView subclasses. 

For example, NSMenu currently reorganizes the menus if they're horizontal.Maybe NSMenu's `_organizeMenu` method should check the theme to see if it wants to handle organizing them, and if so, pass the buck to it? 

Or things like the position and size of the main menu when horizontal; the theme should get a chance to modify that as desired by the theme author.

I have been tinkering with this idea, adding more hooks into various places as I need them, and so far it's working pretty well -- nothing breaks because the GSTheme base implementation of each new hook just does whatever the library was going to do already.

It's nothing terribly fancy or flashy, but it has enabled me to implement a second "global" menubar Z-ordered beneath the per-app one, showing an equivalent to the "Apple" menu, and to have it look the way I want it to.

If there is any interest in expanding GSTheme's ability to customize the presentation, I'd be happy to open a PR with my (very small) changes to `libs-gui`.

![screenshot](https://github.com/gnustep/libs-gui/assets/106450185/99b6fe9c-a56d-4ae6-87c4-c68049d95886)
![screenshot2](https://github.com/gnustep/libs-gui/assets/106450185/e5e099ba-2b8b-418e-a954-2132b0f7f35b)

**Comment by gcasa** [comment]
@KyleCardoza please do add a PR to address this.  The changes you have made in your branch seem to have nice results.  I think changes to GSTheme to allow the same look would be welcome for review.

**Comment by KyleCardoza** [comment]
PR submitted as draft.
