### ISSUE TITLE
Theming must allow define text color per each style

### ISSUE THREAD

**Issue by optimisme** [gnustep/libs-gui#225]
Theming must allow define text color per each style, 

Some button styles must have different text color as seen in the picture, for example the theme must be able to set up the color for  NSRecessedBezelStyle buttons

<img width="1470" alt="Screenshot 2023-12-22 at 11 45 41" src="https://github.com/gnustep/libs-gui/assets/7429620/a774c814-fc93-4459-9994-62e4da66de8c">

**Comment by fredkiefer** [comment]
Could you please explain a bit what you mean by this requirement that you state here? There already is a method 
```
- (void) drawButton: (NSRect)frame 
                 in: (NSCell*)cell 
               view: (NSView*)view 
              style: (int)style 
              state: (GSThemeControlState)state 
```
On GSTheme and by overriding this method in your own theme you should be able to produce about any fancy button that you can think of. Most likely you don't want to do that but would prefer another method to change the appearance of a button without overriding this method. Is this correct? And if so, what is it that you are expecting?
For your specific case NSRecessedBezelStyle this method is actually missing specific code as we were not aware how such a button should look like. If you have suggestions on how to style this sort of button within the GNUstep default style, I am willing to put such code in. And if you make this new code configurable it might also help with your advanced requirements.
In the current code the colour is only influenced by the state of the button not by the style. You will need convincing arguments to get that changed.

**Comment by optimisme** [comment]
The source code of my theme (in development)
https://github.com/optimisme/GNUStep-Theme

I've seen that I can change the text color this way:
        if ([cell isKindOfClass:[NSButtonCell class]]) {
            NSButtonCell *buttonCell = (NSButtonCell *) cell;
            NSString *keyEquivalent = [buttonCell keyEquivalent];
            if ([keyEquivalent isEqualToString:@"\r"]) {
                NSDictionary *attributes = @{NSForegroundColorAttributeName: [NSColor whiteColor]};
                NSAttributedString *coloredTitle = [[NSAttributedString alloc] initWithString:[cell title] attributes:attributes];
                [buttonCell setAttributedTitle:coloredTitle];
                backgroundColor = GVThemeColorRGB(0, 122, 255, 1.0);
            }
        }
        [backgroundColor set];
        [bezelPath fill];
        [bezelColor setStroke];
        [bezelPath setLineWidth:1.0];
        [bezelPath stroke];
        
        Is this the way to color background and text from button cells while doing a theme?

**Comment by optimisme** [comment]
Closing the issue, it is possible to style the text in each custom style:
```objectivec
        NSMutableParagraphStyle *paragraphStyle;
        NSDictionary *attributes;
        NSAttributedString *coloredTitle;
        NSButtonCell *buttonCell = nil;
        if ([cell isKindOfClass:[NSButtonCell class]]) {
            buttonCell = (NSButtonCell *) cell;
        }
        if (buttonCell != nil) {
            bezelColor = GVThemeColorRGB(111, 111, 111, 1.0);
            paragraphStyle = [[NSMutableParagraphStyle alloc] init];
            [paragraphStyle setAlignment:NSTextAlignmentCenter];
            attributes = @{
                NSForegroundColorAttributeName: bezelColor,
                NSParagraphStyleAttributeName: paragraphStyle,
            };
            coloredTitle = [[NSAttributedString alloc] initWithString:[cell title] attributes:attributes];
            [buttonCell setAttributedTitle:coloredTitle];
        }
```
