### ISSUE TITLE
Support NIBArchive format

### ISSUE THREAD

**Issue by gcasa** [gnustep/libs-gui#230]
There is currently a new format for nib files, it is called NIBArchive.   Previously, NIB files were XML files that were, basically, indexed, keyed archives.  Now there is a new binary format.     In the NeXT days it was typedstream, but this is not what it is now either.   Please find the attached example.

[MainMenu.nib.zip](https://github.com/gnustep/libs-gui/files/13762933/MainMenu.nib.zip)

**Comment by fredkiefer** [comment]
The best information I could find for this format is here https://dkimitsa.github.io/2018/02/13/wl-tech-details-2-robovm/

**Comment by gcasa** [comment]
> The best information I could find for this format is here [dkimitsa.github.io/2018/02/13/wl-tech-details-2-robovm](https://dkimitsa.github.io/2018/02/13/wl-tech-details-2-robovm/)

Ah, very cool!  Thanks!

**Comment by gcasa** [comment]
This is very likely not needed.   NIBArchive is a "compiled" format that is created from XIB files defined by Xcode.   So, theoretically, we should be able to support this simply by being able to read XIBs and Storyboards.
