### ISSUE TITLE
NSOutlineView root item vs. nil

### ISSUE THREAD

**Issue by rmottola** [gnustep/libs-gui#306]
The root item of an OutlineView is expected to be nil.
GNUmail (check MailboxManagerController.m reloadAllFolders) calls directly with the root item (in that case an array). Apple apparently deduplicates and works, while GNUstep will descend and expand first nil to the array and then put the array as first level item. Apple somehow "notices" they are the same. [NSOutlineView expandItem]

**Comment by gcasa** [comment]
![outlineViewLazyLoad](https://github.com/user-attachments/assets/f23aed19-8298-4331-a7d6-04fab5ad5ea8)

Here it calls the outlineView data source method with a different method than we do.  We use expandItem: nil, they use _nonStaticDataSourceChild:ofItem:.  While our implementation is functionally correct, and conforms to the documentation, this results in slightly different behavior.  Also, I believe as mentioned above, Apple is deduplicating items per child, so they are only displayed once.   Also see below... the data source is called with item = nil...

![outlineViewLazyLoad2](https://github.com/user-attachments/assets/cb376da7-ec59-43f2-a3aa-31638bef577b)

**Comment by rmottola** [comment]
I think we need to write a test if the duplication is being done per-item or only at the root level.

**Comment by gcasa** [comment]
Tested our theory...
![SameStringTest](https://github.com/user-attachments/assets/bc3b1eaa-dadd-4e7d-991a-40ef6ac01fdd)
It appears it is not deduplicated.  I think what we have is good enough.

**Comment by gcasa** [comment]
Closed, based on the determination above.
