### ISSUE TITLE
NSPanels are not movable under Windows

### ISSUE THREAD

**Issue by gcasa** [gnustep/libs-gui#78]
Same setup as #77. NSPanels do not show properly under Windows, they should be more like NSWindows.

See attached:

![NSAlert](https://user-images.githubusercontent.com/27943/91684735-4b219c80-eb26-11ea-932d-ec8dc25b790b.png)

Also, as you can see, the NSAlert should have an error in it and a button, but it doesn't.

**Comment by gnustep-admin** [comment]
Actually, Panels are okay, it's the alert that isn't working.  I believe it's because on this app it is modal.  It should show a button, but it doesn't. :/   Closing this one.

**Comment by gnustep-admin** [comment]
The NSAlert is not showing its contents...  I will make a minimal test case.
