### ISSUE TITLE
JPEG images will not load properly under MSYS2

### ISSUE THREAD

**Issue by gnustep-admin** [gnustep/libs-gui#79]
MSYS environment set up per instructions on wiki.

Procedure:
1. build LaternaMagica in gap
2. use it to load a JPEG file
3. file fails to load and gives an error... see attached...

![jpeg_error](https://user-images.githubusercontent.com/17712407/91704791-09a2e880-eb4a-11ea-934c-fb4bf745ac22.png)

**Comment by rmottola** [comment]
Issue has been fixed
