### ISSUE TITLE
Tar error while doing make install on Alpine linux

### ISSUE THREAD

**Issue by plaurent** [gnustep/libs-gui#84]
While doing sudo -E make install for libs-gui, installation halts with the following error:

```
Making install for bundle libgmodel...
 Installing headers...
 Installing bundle directory...
tar: f: No such file or directory
tar: short read
make[2]: *** [/usr/GNUstep/System/Library/Makefiles/Instance/Shared/bundle.make:412: shared-instance-bundle-install] Error 1
make[1]: *** [/usr/GNUstep/System/Library/Makefiles/Master/rules.make:297: libgmodel.install.bundle.variables] Error 2
make: *** [/usr/GNUstep/System/Library/Makefiles/Master/serial-subdirectories.make:53: internal-install] Error 2
```

Does anyone know how to address it?

(libs-base built and installed fine.)

**Comment by gcasa** [comment]
What are you using to install?  More detail needed.

**Comment by fredkiefer** [comment]
Could you please run the "make install" with messages=YES? This should provide more output about the failing tar command. Most likely it is the tar version you are using that causes this issue. Could you please try to find out which tar gets used here?

**Comment by gcasa** [comment]
@plaurent are you still having this issue?

**Comment by plaurent** [comment]
I will try again when I have the chance, if I see it again with the newer code I’ll re-open this issue — thank you.
