### ISSUE TITLE
GraphicContext isn't ready right after an application did finish launching

### ISSUE THREAD

**Issue by svgol** [gnustep/libs-gui#93]
I have a simple demo application https://github.com/svgol/colorseeker  to demonstrate the issue.
The application shows a color NSBox rounded by 4 sliders controlling RGB and alpha.
When my application did finish launching the method -[showText:] sets the color of NSBox
controlled by values of sliders. It doesn't happen at once. Only several consecutive calls of the method
eventually do that. I temporarily implemented -[windowDidUpdate:] with a counter of calls (in the code the variable **_updates**).
It takes 8-10 calls on my system to eventually get the NSBox colored. I tried different backends (cairo, art, xlib)
at no avail.

Here are screenshots https://svgol.github.io . 

P.S. My system is Linux Ubuntu x64 on Intel i5, Xorg, the current gnustep base-gui-back .

**Comment by fredkiefer** [comment]
I tried to reproduce your issue and after looking at your code I am surprised that you get any results at all. The code and the whole application are broken in so many ways that I will most likely forget a few when listing these here.

A GNUstep (or Cocoa) application is only allowed to draw anything from within the drawRect: method of a view. This method gets called from one of the various displayXXX methods. You try to draw from somewhere else and this is mould to fail.
You set the values of the slide from the update: method. This method gets called when ever the window needs updating. This will block the possibility of changing the sliders. It would be better to set the slider values in the awakeFromNib method.
Although you call the view that you use to display the colour in colorBox, it is not the NSBox that is present in the window but a view within that box. If you remove that view you could just set the colour of the NSBox in your showText: method and the display should happen automatically.

I am closing this issue as this has really nothing to do with GNUstep.
