### ISSUE TITLE
Autoenable message sent to dellocated menu item

### ISSUE THREAD

**Issue by rmottola** [gnustep/libs-gui#94]
Comment with more details @gcasa .
Debugging GNUMail crash, I have a stacktrace where autoenabel is asked for an item while the whole popupbutton is being deallocated.

Setting
  [sendSupportedMechanismsPopUp setAutoenablesItems:NO];
"cures" the issue but Gregory agrees it is more a workaround.

A question is also, should the default be YES or NO for autoenable? Gorm creates PopUpButtons with YES but apparently Mac no (@gcasa  please integrate/correct with the results of your test)

Full stacktrace when putting a zombie breakpoint:
```
#0  GSLogZombie (sel=0xb7c21cd0 <_OBJC_SELECTOR_TABLE+2032>, o=0xb8ba28) at NSObject.m:181
#1  -[NSZombie forwardInvocation:] (self=0xb8ba28, _cmd=0xb7742610 <_OBJC_SELECTOR_TABLE+176>,
    anInvocation=0xecd0a8) at NSObject.m:2523
#2  0xb74253e3 in GSFFIInvocationCallback (cif=0xec8b70, retp=0xbfffe990, args=0xbfffe920, user=0xeb3d58)
    at GSFFIInvocation.m:606
#3  0xb4c03b45 in ?? () from /usr/lib/i386-linux-gnu/libffi.so.6
#4  0xb4c03ef6 in ?? () from /usr/lib/i386-linux-gnu/libffi.so.6
#5  0xb784f78e in -[NSApplication targetForAction:to:from:] (self=0x53a880,
    _cmd=0xb7c88e08 <_OBJC_SELECTOR_TABLE+1192>, theAction=0xb3aed118 <_OBJC_SELECTOR_TABLE+1304>,
    theTarget=0xb8ba28, sender=0xc01e20) at NSApplication.m:2294
#6  0xb790a075 in -[NSMenu _autoenableItem:] (self=0xc0fb70,
    _cmd=0xb7c88e68 <_OBJC_SELECTOR_TABLE+1288>, item=0xc01e20) at NSMenu.m:1177
#7  0xb790ef71 in -[NSMenu update] (self=<optimized out>, _cmd=<optimized out>) at NSMenu.m:1255
#8  0xb7932b82 in -[NSPopUpButtonCell setMenu:] (self=0xc0faa8,
    _cmd=0xb7ca18f0 <_OBJC_SELECTOR_TABLE+112>, menu=0x0) at NSPopUpButtonCell.m:173
#9  0xb7934dda in -[NSPopUpButtonCell dealloc] (self=0xc0faa8, _cmd=0xb76f4f58 <_OBJC_SELECTOR_TABLE+24>)
    at NSPopUpButtonCell.m:152
#10 0xb78a834f in -[NSControl dealloc] (self=0xc0f9d8, _cmd=0xb76f4f58 <_OBJC_SELECTOR_TABLE+24>)
    at NSControl.m:125
#11 0xb79b94c7 in -[NSView removeSubview:] (self=0xc38310, _cmd=0xb7cf0038 <_OBJC_SELECTOR_TABLE+1528>,
    aView=0xc0f9d8) at NSView.m:965
#12 0xb79b92c5 in -[NSView removeFromSuperviewWithoutNeedingDisplay] (self=0xc0f9d8,
    _cmd=0xb7ceffa0 <_OBJC_SELECTOR_TABLE+1376>) at NSView.m:908
#13 0xb79c7972 in -[NSView dealloc] (self=0xc38310, _cmd=0xb3af1898 <_OBJC_SELECTOR_TABLE+824>)
    at NSView.m:745
#14 0xb3acf38a in -[SendSMTPView dealloc] (self=0xc38310, _cmd=0xb76f4f58 <_OBJC_SELECTOR_TABLE+24>)
    at SendView.m:146
#15 0xb79b94c7 in -[NSView removeSubview:] (self=0xc32078, _cmd=0xb7cf0038 <_OBJC_SELECTOR_TABLE+1528>,
    aView=0xc38310) at NSView.m:965
#16 0xb79b92c5 in -[NSView removeFromSuperviewWithoutNeedingDisplay] (self=0xc38310,
    _cmd=0xb7ceffa0 <_OBJC_SELECTOR_TABLE+1376>) at NSView.m:908
```

**Comment by fredkiefer** [comment]
To me this looks like an application issue. The menu in the popup button, that is being remove seems to have a reference to an object that was already deallocated. The only thing that gui could do here is the workaround you suggested, just on the menu instead of the popup. And if this is not what you want then on this level no solution is possible. You should instead try to fix the application to release the popup button before releasing the referenced object.

**Comment by rmottola** [comment]
Discussing and analyzing, it is not specific an application issue (although the application could be changed not to trigger this issue with no harm) the referenced object is the window controller itself in this case.

**Comment by fredkiefer** [comment]
I committed some sort of a workaround for this issue. Could you please try whether this resolves the problem and won't cause other issues?

**Comment by fredkiefer** [comment]
Closing this as there was no reply.

**Comment by rmottola** [comment]
I did a test on two systems and all seems fine now and I have not noticed side-effects.
