### ISSUE TITLE
Feature Request: Tool to compare APIs

### ISSUE THREAD

**Issue by Letterus** [gnustep/libs-gui#97]
It would be great to have a tool that compares the GNUstep API to the one of Cocoa automatically. I do *not* mean a test suite that tests functionality of each class (nice to have, but very much manual work). I mean a tool that automatically generates a table putting the (method) signatures of each class side by side and highlights differences between class definitions.

Having this would be a great effort in gaining real compatibility I think.

Personally I do not need the full API of SDK 10.15 or something of AppKit. If we could have the set of classes of SDK 10.6/10.7 adopt them to the API of a current SDK and get them stable and working and then maybe even do some cosmestics to make the controls look better, that would be *great* gain.

**Comment by fredkiefer** [comment]
It should be fairly easy to write such a tool based on objc_getClassList and friends. First you list all classes and for each class the methods and properties, output these sorted into a file and do the same on the other system.
But this wouldn't help you in the way you think it would. Many methods are present in GNUstep but the implementation is basically empty. There is no way how this tool would spot such methods. This is a lot easier for a human :-) And in the end, even if the method is implemented it still may be incomplete. You always need to test one you rely on GNUstep code.

I do not see this as a useful request for GNUstep gui and close it for this reason.

**Comment by Letterus** [comment]
Ok, thank you. @gcasa, just to let you know. I don't know of a better way currently (ok, unit tests of course, but I think nobody has time to do that).

Maybe I'm going to try one of these approaches:

1. Just use Doxygen and compare output: http://web.archive.org/web/20130923000537/http://www.duckrowing.com/2010/03/18/documenting-objective-c-with-doxygen-part-i/
2. Try to generate UML using OmniGraffle and compare the graphs: https://stackoverflow.com/questions/6079312/how-can-i-generate-uml-diagrams-from-xcode4
